INPUT_FILENAME:
  Charges: data/Data/Charges_use.csv
  Damages: data/Data/Damages_use.csv
  Endorse: data/Data/Endorse_use.csv
  Primary_Person: data/Data/Primary_Person_use.csv
  Units: data/Data/Units_use.csv
  Restrict: data/Data/Restrict_use.csv

OUTPUT_PATH:
  1: ./Output/1
  2: ./Output/2
  3: ./Output/3
  4: ./Output/4
  5: ./Output/5
  6: ./Output/6
  7: ./Output/7
  8: ./Output/8
  9: ./Output/9
  10: ./Output/10

FILE_FORMAT:
  Output: csv
